//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ApiServiceSoapBinding", Namespace="https://api.monopond.com/fax/soap/v2")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(apiResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(apiRequest))]
public partial class ApiService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback PauseFaxOperationCompleted;
    
    private System.Threading.SendOrPostCallback ResumeFaxOperationCompleted;
    
    private System.Threading.SendOrPostCallback FaxStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback StopFaxOperationCompleted;
    
    private System.Threading.SendOrPostCallback SendFaxOperationCompleted;

    public Security security;

    /// <remarks/>
    public ApiService(String apiUrl, String username, String password)
    {
        //this.Url = "https://api.monopond.com/fax/soap/v2/";
        this.Url = apiUrl;
        if (security == null)
        {
            security = new Security();
            security.UsernameToken = new UsernameToken(username, password);
        }
    }
    
    /// <remarks/>
    public event PauseFaxCompletedEventHandler PauseFaxCompleted;
    
    /// <remarks/>
    public event ResumeFaxCompletedEventHandler ResumeFaxCompleted;
    
    /// <remarks/>
    public event FaxStatusCompletedEventHandler FaxStatusCompleted;
    
    /// <remarks/>
    public event StopFaxCompletedEventHandler StopFaxCompleted;
    
    /// <remarks/>
    public event SendFaxCompletedEventHandler SendFaxCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("PauseFaxResponse", Namespace="https://api.monopond.com/fax/soap/v2", IsNullable=true)]
    [SoapHeader("security")]
    public pauseFaxResponse PauseFax([System.Xml.Serialization.XmlElementAttribute(Namespace="https://api.monopond.com/fax/soap/v2", IsNullable=true)] pauseFaxRequest PauseFaxRequest) {
        object[] results = this.Invoke("PauseFax", new object[] {
                    PauseFaxRequest});
        return ((pauseFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPauseFax(pauseFaxRequest PauseFaxRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PauseFax", new object[] {
                    PauseFaxRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public pauseFaxResponse EndPauseFax(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((pauseFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public void PauseFaxAsync(pauseFaxRequest PauseFaxRequest) {
        this.PauseFaxAsync(PauseFaxRequest, null);
    }
    
    /// <remarks/>
    public void PauseFaxAsync(pauseFaxRequest PauseFaxRequest, object userState) {
        if ((this.PauseFaxOperationCompleted == null)) {
            this.PauseFaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPauseFaxOperationCompleted);
        }
        this.InvokeAsync("PauseFax", new object[] {
                    PauseFaxRequest}, this.PauseFaxOperationCompleted, userState);
    }
    
    private void OnPauseFaxOperationCompleted(object arg) {
        if ((this.PauseFaxCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PauseFaxCompleted(this, new PauseFaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("ResumeFaxResponse", Namespace = "https://api.monopond.com/fax/soap/v2", IsNullable = true)]
    [SoapHeader("security")]
    public resumeFaxResponse ResumeFax([System.Xml.Serialization.XmlElementAttribute(Namespace="https://api.monopond.com/fax/soap/v2", IsNullable=true)] resumeFaxRequest ResumeFaxRequest) {
        object[] results = this.Invoke("ResumeFax", new object[] {
                    ResumeFaxRequest});
        return ((resumeFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginResumeFax(resumeFaxRequest ResumeFaxRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ResumeFax", new object[] {
                    ResumeFaxRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public resumeFaxResponse EndResumeFax(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((resumeFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public void ResumeFaxAsync(resumeFaxRequest ResumeFaxRequest) {
        this.ResumeFaxAsync(ResumeFaxRequest, null);
    }
    
    /// <remarks/>
    public void ResumeFaxAsync(resumeFaxRequest ResumeFaxRequest, object userState) {
        if ((this.ResumeFaxOperationCompleted == null)) {
            this.ResumeFaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResumeFaxOperationCompleted);
        }
        this.InvokeAsync("ResumeFax", new object[] {
                    ResumeFaxRequest}, this.ResumeFaxOperationCompleted, userState);
    }
    
    private void OnResumeFaxOperationCompleted(object arg) {
        if ((this.ResumeFaxCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ResumeFaxCompleted(this, new ResumeFaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("FaxStatusResponse", Namespace="https://api.monopond.com/fax/soap/v2")]
    [SoapHeader("security")]
    public faxStatusResponse FaxStatus([System.Xml.Serialization.XmlElementAttribute(Namespace="https://api.monopond.com/fax/soap/v2", IsNullable=true)] faxStatusRequest FaxStatusRequest) {
        object[] results = this.Invoke("FaxStatus", new object[] {
                    FaxStatusRequest});
        return ((faxStatusResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginFaxStatus(faxStatusRequest FaxStatusRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("FaxStatus", new object[] {
                    FaxStatusRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public faxStatusResponse EndFaxStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((faxStatusResponse)(results[0]));
    }
    
    /// <remarks/>
    public void FaxStatusAsync(faxStatusRequest FaxStatusRequest) {
        this.FaxStatusAsync(FaxStatusRequest, null);
    }
    
    /// <remarks/>
    public void FaxStatusAsync(faxStatusRequest FaxStatusRequest, object userState) {
        if ((this.FaxStatusOperationCompleted == null)) {
            this.FaxStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFaxStatusOperationCompleted);
        }
        this.InvokeAsync("FaxStatus", new object[] {
                    FaxStatusRequest}, this.FaxStatusOperationCompleted, userState);
    }
    
    private void OnFaxStatusOperationCompleted(object arg) {
        if ((this.FaxStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.FaxStatusCompleted(this, new FaxStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("StopFaxResponse", Namespace = "https://api.monopond.com/fax/soap/v2", IsNullable = true)]
    [SoapHeader("security")]
    public stopFaxResponse StopFax([System.Xml.Serialization.XmlElementAttribute(Namespace="https://api.monopond.com/fax/soap/v2", IsNullable=true)] stopFaxRequest StopFaxRequest) {
        object[] results = this.Invoke("StopFax", new object[] {
                    StopFaxRequest});
        return ((stopFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginStopFax(stopFaxRequest StopFaxRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("StopFax", new object[] {
                    StopFaxRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public stopFaxResponse EndStopFax(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((stopFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public void StopFaxAsync(stopFaxRequest StopFaxRequest) {
        this.StopFaxAsync(StopFaxRequest, null);
    }
    
    /// <remarks/>
    public void StopFaxAsync(stopFaxRequest StopFaxRequest, object userState) {
        if ((this.StopFaxOperationCompleted == null)) {
            this.StopFaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStopFaxOperationCompleted);
        }
        this.InvokeAsync("StopFax", new object[] {
                    StopFaxRequest}, this.StopFaxOperationCompleted, userState);
    }
    
    private void OnStopFaxOperationCompleted(object arg) {
        if ((this.StopFaxCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.StopFaxCompleted(this, new StopFaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
    [return: System.Xml.Serialization.XmlElementAttribute("SendFaxResponse", Namespace="https://api.monopond.com/fax/soap/v2", IsNullable=true)]
    [SoapHeader("security")]
    public sendFaxResponse SendFax([System.Xml.Serialization.XmlElementAttribute(Namespace="https://api.monopond.com/fax/soap/v2", IsNullable=true)] sendFaxRequest SendFaxRequest) {
        Console.WriteLine("sending fax message...");

        object[] results = this.Invoke("SendFax", new object[] {
                    SendFaxRequest});
        return ((sendFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSendFax(sendFaxRequest SendFaxRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SendFax", new object[] {
                    SendFaxRequest}, callback, asyncState);
    }
    
    /// <remarks/>
    public sendFaxResponse EndSendFax(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((sendFaxResponse)(results[0]));
    }
    
    /// <remarks/>
    public void SendFaxAsync(sendFaxRequest SendFaxRequest) {
        this.SendFaxAsync(SendFaxRequest, null);
    }
    
    /// <remarks/>
    public void SendFaxAsync(sendFaxRequest SendFaxRequest, object userState) {
        if ((this.SendFaxOperationCompleted == null)) {
            this.SendFaxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFaxOperationCompleted);
        }
        this.InvokeAsync("SendFax", new object[] {
                    SendFaxRequest}, this.SendFaxOperationCompleted, userState);
    }
    
    private void OnSendFaxOperationCompleted(object arg) {
        if ((this.SendFaxCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SendFaxCompleted(this, new SendFaxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class pauseFaxRequest : apiRequest {
    
    private string messageRefField;
    
    private string sendRefField;
    
    private string broadcastRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageRef {
        get {
            return this.messageRefField;
        }
        set {
            this.messageRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendRef {
        get {
            return this.sendRefField;
        }
        set {
            this.sendRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BroadcastRef {
        get {
            return this.broadcastRefField;
        }
        set {
            this.broadcastRefField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sendFaxRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(stopFaxRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(faxStatusRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resumeFaxRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(pauseFaxRequest))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public abstract partial class apiRequest {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class faxErrorAdapter {
    
    private string codeField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class apiFaxMessageStatusResults {
    
    private faxErrorAdapter errorField;
    
    private int attemptField;
    
    private bool attemptFieldSpecified;
    
    private faxResult resultField;
    
    private bool resultFieldSpecified;
    
    private string costField;
    
    private int pagesField;
    
    private bool pagesFieldSpecified;
    
    private int totalFaxDurationField;
    
    private bool totalFaxDurationFieldSpecified;
    
    private System.DateTime scheduledStartTimeField;
    
    private bool scheduledStartTimeFieldSpecified;
    
    private System.DateTime dateCallStartedField;
    
    private bool dateCallStartedFieldSpecified;
    
    private System.DateTime dateCallEndedField;
    
    private bool dateCallEndedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public faxErrorAdapter Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int attempt {
        get {
            return this.attemptField;
        }
        set {
            this.attemptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool attemptSpecified {
        get {
            return this.attemptFieldSpecified;
        }
        set {
            this.attemptFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public faxResult result {
        get {
            return this.resultField;
        }
        set {
            this.resultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool resultSpecified {
        get {
            return this.resultFieldSpecified;
        }
        set {
            this.resultFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int pages {
        get {
            return this.pagesField;
        }
        set {
            this.pagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pagesSpecified {
        get {
            return this.pagesFieldSpecified;
        }
        set {
            this.pagesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int totalFaxDuration {
        get {
            return this.totalFaxDurationField;
        }
        set {
            this.totalFaxDurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalFaxDurationSpecified {
        get {
            return this.totalFaxDurationFieldSpecified;
        }
        set {
            this.totalFaxDurationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime scheduledStartTime {
        get {
            return this.scheduledStartTimeField;
        }
        set {
            this.scheduledStartTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool scheduledStartTimeSpecified {
        get {
            return this.scheduledStartTimeFieldSpecified;
        }
        set {
            this.scheduledStartTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime dateCallStarted {
        get {
            return this.dateCallStartedField;
        }
        set {
            this.dateCallStartedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCallStartedSpecified {
        get {
            return this.dateCallStartedFieldSpecified;
        }
        set {
            this.dateCallStartedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime dateCallEnded {
        get {
            return this.dateCallEndedField;
        }
        set {
            this.dateCallEndedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCallEndedSpecified {
        get {
            return this.dateCallEndedFieldSpecified;
        }
        set {
            this.dateCallEndedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public enum faxResult {
    
    /// <remarks/>
    success,
    
    /// <remarks/>
    blocked,
    
    /// <remarks/>
    failed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class apiFaxMessageStatusDetails {
    
    private string sendFromField;
    
    private faxResolution resolutionField;
    
    private bool resolutionFieldSpecified;
    
    private int retriesField;
    
    private bool retriesFieldSpecified;
    
    private int busyRetriesField;
    
    private bool busyRetriesFieldSpecified;
    
    private string headerFormatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sendFrom {
        get {
            return this.sendFromField;
        }
        set {
            this.sendFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public faxResolution resolution {
        get {
            return this.resolutionField;
        }
        set {
            this.resolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool resolutionSpecified {
        get {
            return this.resolutionFieldSpecified;
        }
        set {
            this.resolutionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int retries {
        get {
            return this.retriesField;
        }
        set {
            this.retriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool retriesSpecified {
        get {
            return this.retriesFieldSpecified;
        }
        set {
            this.retriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int busyRetries {
        get {
            return this.busyRetriesField;
        }
        set {
            this.busyRetriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool busyRetriesSpecified {
        get {
            return this.busyRetriesFieldSpecified;
        }
        set {
            this.busyRetriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string headerFormat {
        get {
            return this.headerFormatField;
        }
        set {
            this.headerFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public enum faxResolution {
    
    /// <remarks/>
    normal,
    
    /// <remarks/>
    fine,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class apiFaxMessageStatus {
    
    private apiFaxMessageStatusDetails faxDetailsField;
    
    private apiFaxMessageStatusResults[] faxResultsField;
    
    private string messageRefField;
    
    private string sendRefField;
    
    private string broadcastRefField;
    
    private string sendToField;
    
    private faxUserStatus statusField;
    
    private bool statusFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public apiFaxMessageStatusDetails FaxDetails {
        get {
            return this.faxDetailsField;
        }
        set {
            this.faxDetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FaxResult", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public apiFaxMessageStatusResults[] FaxResults {
        get {
            return this.faxResultsField;
        }
        set {
            this.faxResultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string messageRef {
        get {
            return this.messageRefField;
        }
        set {
            this.messageRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sendRef {
        get {
            return this.sendRefField;
        }
        set {
            this.sendRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string broadcastRef {
        get {
            return this.broadcastRefField;
        }
        set {
            this.broadcastRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sendTo {
        get {
            return this.sendToField;
        }
        set {
            this.sendToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public faxUserStatus status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool statusSpecified {
        get {
            return this.statusFieldSpecified;
        }
        set {
            this.statusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public enum faxUserStatus {
    
    /// <remarks/>
    pending,
    
    /// <remarks/>
    processing,
    
    /// <remarks/>
    queued,
    
    /// <remarks/>
    starting,
    
    /// <remarks/>
    sending,
    
    /// <remarks/>
    pausing,
    
    /// <remarks/>
    paused,
    
    /// <remarks/>
    resuming,
    
    /// <remarks/>
    stopping,
    
    /// <remarks/>
    finalizing,
    
    /// <remarks/>
    done,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class faxResultsTotals {
    
    private long successField;
    
    private bool successFieldSpecified;
    
    private long blockedField;
    
    private bool blockedFieldSpecified;
    
    private long failedField;
    
    private bool failedFieldSpecified;
    
    private long totalAttemptsField;
    
    private bool totalAttemptsFieldSpecified;
    
    private long totalFaxDurationField;
    
    private bool totalFaxDurationFieldSpecified;
    
    private long totalPagesField;
    
    private bool totalPagesFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long success {
        get {
            return this.successField;
        }
        set {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool successSpecified {
        get {
            return this.successFieldSpecified;
        }
        set {
            this.successFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long blocked {
        get {
            return this.blockedField;
        }
        set {
            this.blockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool blockedSpecified {
        get {
            return this.blockedFieldSpecified;
        }
        set {
            this.blockedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long failed {
        get {
            return this.failedField;
        }
        set {
            this.failedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool failedSpecified {
        get {
            return this.failedFieldSpecified;
        }
        set {
            this.failedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long totalAttempts {
        get {
            return this.totalAttemptsField;
        }
        set {
            this.totalAttemptsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalAttemptsSpecified {
        get {
            return this.totalAttemptsFieldSpecified;
        }
        set {
            this.totalAttemptsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long totalFaxDuration {
        get {
            return this.totalFaxDurationField;
        }
        set {
            this.totalFaxDurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalFaxDurationSpecified {
        get {
            return this.totalFaxDurationFieldSpecified;
        }
        set {
            this.totalFaxDurationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long totalPages {
        get {
            return this.totalPagesField;
        }
        set {
            this.totalPagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalPagesSpecified {
        get {
            return this.totalPagesFieldSpecified;
        }
        set {
            this.totalPagesFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class faxStatusTotals {
    
    private long pendingField;
    
    private bool pendingFieldSpecified;
    
    private long processingField;
    
    private bool processingFieldSpecified;
    
    private long queuedField;
    
    private bool queuedFieldSpecified;
    
    private long startingField;
    
    private bool startingFieldSpecified;
    
    private long sendingField;
    
    private bool sendingFieldSpecified;
    
    private long finalizingField;
    
    private bool finalizingFieldSpecified;
    
    private long doneField;
    
    private bool doneFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long pending {
        get {
            return this.pendingField;
        }
        set {
            this.pendingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pendingSpecified {
        get {
            return this.pendingFieldSpecified;
        }
        set {
            this.pendingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long processing {
        get {
            return this.processingField;
        }
        set {
            this.processingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool processingSpecified {
        get {
            return this.processingFieldSpecified;
        }
        set {
            this.processingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long queued {
        get {
            return this.queuedField;
        }
        set {
            this.queuedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool queuedSpecified {
        get {
            return this.queuedFieldSpecified;
        }
        set {
            this.queuedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long starting {
        get {
            return this.startingField;
        }
        set {
            this.startingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool startingSpecified {
        get {
            return this.startingFieldSpecified;
        }
        set {
            this.startingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long sending {
        get {
            return this.sendingField;
        }
        set {
            this.sendingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sendingSpecified {
        get {
            return this.sendingFieldSpecified;
        }
        set {
            this.sendingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long finalizing {
        get {
            return this.finalizingField;
        }
        set {
            this.finalizingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool finalizingSpecified {
        get {
            return this.finalizingFieldSpecified;
        }
        set {
            this.finalizingFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long done {
        get {
            return this.doneField;
        }
        set {
            this.doneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool doneSpecified {
        get {
            return this.doneFieldSpecified;
        }
        set {
            this.doneFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(faxStatusResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sendFaxResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(stopFaxResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resumeFaxResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(pauseFaxResponse))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class apiResponse {
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sendFaxResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(stopFaxResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(resumeFaxResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(pauseFaxResponse))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class faxStatusResponse : apiResponse {
    
    private faxStatusTotals faxStatusTotalsField;
    
    private faxResultsTotals faxResultsTotalsField;
    
    private apiFaxMessageStatus[] faxMessagesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public faxStatusTotals FaxStatusTotals {
        get {
            return this.faxStatusTotalsField;
        }
        set {
            this.faxStatusTotalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public faxResultsTotals FaxResultsTotals {
        get {
            return this.faxResultsTotalsField;
        }
        set {
            this.faxResultsTotalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FaxMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public apiFaxMessageStatus[] FaxMessages {
        get {
            return this.faxMessagesField;
        }
        set {
            this.faxMessagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class sendFaxResponse : faxStatusResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class stopFaxResponse : faxStatusResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class resumeFaxResponse : faxStatusResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class pauseFaxResponse : faxStatusResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class apiFaxMessageBlocklist {
    
    private bool dncrField;
    
    private bool dncrFieldSpecified;
    
    private bool fpsField;
    
    private bool fpsFieldSpecified;
    
    private bool smartblockField;
    
    private bool smartblockFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool dncr {
        get {
            return this.dncrField;
        }
        set {
            this.dncrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dncrSpecified {
        get {
            return this.dncrFieldSpecified;
        }
        set {
            this.dncrFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool fps {
        get {
            return this.fpsField;
        }
        set {
            this.fpsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fpsSpecified {
        get {
            return this.fpsFieldSpecified;
        }
        set {
            this.fpsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool smartblock {
        get {
            return this.smartblockField;
        }
        set {
            this.smartblockField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool smartblockSpecified {
        get {
            return this.smartblockFieldSpecified;
        }
        set {
            this.smartblockFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class apiFaxDocument {
    
    private string fileNameField;
    
    private string fileDataField;
    
    private int orderField;
    
    public apiFaxDocument() {
        this.orderField = 0;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileName {
        get {
            return this.fileNameField;
        }
        set {
            this.fileNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileData {
        get {
            return this.fileDataField;
        }
        set {
            this.fileDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class apiFaxMessage {
    
    private string messageRefField;
    
    private string sendToField;
    
    private string sendFromField;
    
    private apiFaxDocument[] documentsField;
    
    private faxResolution resolutionField;
    
    private bool resolutionFieldSpecified;
    
    private apiFaxMessageBlocklist blocklistsField;
    
    private string scheduledStartTimeField;
    
    private int retriesField;
    
    private bool retriesFieldSpecified;
    
    private int busyRetriesField;
    
    private bool busyRetriesFieldSpecified;
    
    private string headerFormatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageRef {
        get {
            return this.messageRefField;
        }
        set {
            this.messageRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendTo {
        get {
            return this.sendToField;
        }
        set {
            this.sendToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendFrom {
        get {
            return this.sendFromField;
        }
        set {
            this.sendFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public apiFaxDocument[] Documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public faxResolution Resolution {
        get {
            return this.resolutionField;
        }
        set {
            this.resolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResolutionSpecified {
        get {
            return this.resolutionFieldSpecified;
        }
        set {
            this.resolutionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public apiFaxMessageBlocklist Blocklists {
        get {
            return this.blocklistsField;
        }
        set {
            this.blocklistsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ScheduledStartTime {
        get {
            return this.scheduledStartTimeField;
        }
        set {
            this.scheduledStartTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Retries {
        get {
            return this.retriesField;
        }
        set {
            this.retriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RetriesSpecified {
        get {
            return this.retriesFieldSpecified;
        }
        set {
            this.retriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int BusyRetries {
        get {
            return this.busyRetriesField;
        }
        set {
            this.busyRetriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BusyRetriesSpecified {
        get {
            return this.busyRetriesFieldSpecified;
        }
        set {
            this.busyRetriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeaderFormat {
        get {
            return this.headerFormatField;
        }
        set {
            this.headerFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class sendFaxRequest : apiRequest {
    
    private string broadcastRefField;
    
    private string sendRefField;
    
    private apiFaxMessage[] faxMessagesField;
    
    private apiFaxDocument[] documentsField;
    
    private faxResolution resolutionField;
    
    private bool resolutionFieldSpecified;
    
    private apiFaxMessageBlocklist blocklistsField;
    
    private string sendFromField;
    
    private string scheduledStartTimeField;
    
    private int retriesField;
    
    private bool retriesFieldSpecified;
    
    private int busyRetriesField;
    
    private bool busyRetriesFieldSpecified;
    
    private string headerFormatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BroadcastRef {
        get {
            return this.broadcastRefField;
        }
        set {
            this.broadcastRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendRef {
        get {
            return this.sendRefField;
        }
        set {
            this.sendRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("FaxMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public apiFaxMessage[] FaxMessages {
        get {
            return this.faxMessagesField;
        }
        set {
            this.faxMessagesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public apiFaxDocument[] Documents {
        get {
            return this.documentsField;
        }
        set {
            this.documentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public faxResolution Resolution {
        get {
            return this.resolutionField;
        }
        set {
            this.resolutionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ResolutionSpecified {
        get {
            return this.resolutionFieldSpecified;
        }
        set {
            this.resolutionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public apiFaxMessageBlocklist Blocklists {
        get {
            return this.blocklistsField;
        }
        set {
            this.blocklistsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendFrom {
        get {
            return this.sendFromField;
        }
        set {
            this.sendFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ScheduledStartTime {
        get {
            return this.scheduledStartTimeField;
        }
        set {
            this.scheduledStartTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int Retries {
        get {
            return this.retriesField;
        }
        set {
            this.retriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RetriesSpecified {
        get {
            return this.retriesFieldSpecified;
        }
        set {
            this.retriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int BusyRetries {
        get {
            return this.busyRetriesField;
        }
        set {
            this.busyRetriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BusyRetriesSpecified {
        get {
            return this.busyRetriesFieldSpecified;
        }
        set {
            this.busyRetriesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HeaderFormat {
        get {
            return this.headerFormatField;
        }
        set {
            this.headerFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class stopFaxRequest : apiRequest {
    
    private string messageRefField;
    
    private string sendRefField;
    
    private string broadcastRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageRef {
        get {
            return this.messageRefField;
        }
        set {
            this.messageRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendRef {
        get {
            return this.sendRefField;
        }
        set {
            this.sendRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BroadcastRef {
        get {
            return this.broadcastRefField;
        }
        set {
            this.broadcastRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class faxStatusRequest : apiRequest {
    
    private string messageRefField;
    
    private string sendRefField;
    
    private string broadcastRefField;
    
    private faxStatusLevel verbosityField;
    
    public faxStatusRequest() {
        this.verbosityField = faxStatusLevel.brief;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageRef {
        get {
            return this.messageRefField;
        }
        set {
            this.messageRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendRef {
        get {
            return this.sendRefField;
        }
        set {
            this.sendRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BroadcastRef {
        get {
            return this.broadcastRefField;
        }
        set {
            this.broadcastRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.ComponentModel.DefaultValueAttribute(faxStatusLevel.brief)]
    public faxStatusLevel Verbosity {
        get {
            return this.verbosityField;
        }
        set {
            this.verbosityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public enum faxStatusLevel {
    
    /// <remarks/>
    brief,
    
    /// <remarks/>
    send,
    
    /// <remarks/>
    details,
    
    /// <remarks/>
    results,
    
    /// <remarks/>
    all,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.monopond.com/fax/soap/v2")]
public partial class resumeFaxRequest : apiRequest {
    
    private string messageRefField;
    
    private string sendRefField;
    
    private string broadcastRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MessageRef {
        get {
            return this.messageRefField;
        }
        set {
            this.messageRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SendRef {
        get {
            return this.sendRefField;
        }
        set {
            this.sendRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BroadcastRef {
        get {
            return this.broadcastRefField;
        }
        set {
            this.broadcastRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void PauseFaxCompletedEventHandler(object sender, PauseFaxCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PauseFaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PauseFaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public pauseFaxResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((pauseFaxResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void ResumeFaxCompletedEventHandler(object sender, ResumeFaxCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ResumeFaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ResumeFaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public resumeFaxResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((resumeFaxResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void FaxStatusCompletedEventHandler(object sender, FaxStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class FaxStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal FaxStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public faxStatusResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((faxStatusResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void StopFaxCompletedEventHandler(object sender, StopFaxCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StopFaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal StopFaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public stopFaxResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((stopFaxResponse)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
public delegate void SendFaxCompletedEventHandler(object sender, SendFaxCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SendFaxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SendFaxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public sendFaxResponse Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((sendFaxResponse)(this.results[0]));
        }
    }
}

public class UsernameToken
{
    private String usernameField;
    public string Username {
        get { return this.usernameField; }
        set { this.usernameField = value; }
    }

    private String passwordField;
    public string Password {
        get { return this.passwordField; }
        set { this.passwordField = value; }
    }

    public UsernameToken(string username, string password)
    {
        this.Username = username;
        this.Password = password;
    }

    public UsernameToken() { }
}

[XmlRoot("Security", Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd")]
public class Security : SoapHeader
{
    public UsernameToken UsernameToken;

    public Security()
    {
        MustUnderstand = true;
    }

}